# Generated by Django 5.1.2 on 2024-10-20 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paypal_client_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paypal_client_secret',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_account_id',
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('store_description', models.TextField(blank=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=255)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
