# Generated by Django 5.1.2 on 2024-10-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltymember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.loyaltymember'),
        ),
    ]
